humpbackdev/generator-humpback

generators/app/index.js
generators/app/templates/composer.json
package.json

Needs https://github.com/humpbackdev/humpback/pull/24 and a new tag on humpback repo.

Update drush version to 9.

---

generators/app/index.js
package.json

Needs https://github.com/humpbackdev/humpback/pull/27 merged.

Declare volumes as delegated.

---

generators/app/index.js
generators/app/templates/_composer.json
package.json

Update composer.json file to allow `composer require <project>` commands to work.
Also make a minor change in mysql config.

Update composer json and mysql config.

---

generators/app/index.js
generators/app/templates/_docker-compose.yml
generators/app/templates/_site.ahoy.yml
package.json

Closes #49 
Closes #46 
Depends on https://github.com/humpbackdev/humpback/pull/30

49: Add new ahoy composer command.

---

generators/app/templates/circleci/config.yml
generators/app/templates/pantheon.yml
package.json

The build process and site generation should works as expected

Chaging the CI base image to kporras07/docker-drupal-nginx:php-7.2.x

---

generators/app/index.js
generators/app/templates/_docker-compose.yml
generators/app/templates/env
package.json

51: Add container uid.

---

generators/app/index.js
generators/app/templates/_docker-compose.yml
generators/app/templates/env
package.json

52: Use new php image and add new env vars.

---

generators/app/templates/_composer.json
generators/app/templates/_site.ahoy.yml
generators/app/templates/circleci/settings.secret.php
generators/app/templates/settings/settings.php
generators/app/templates/tests/behat/features/bootstrap/Devinci/DevinciExtension/Context/DebugContext.php
generators/app/templates/tests/behat/features/bootstrap/Devinci/DevinciExtension/Context/JavascriptContext.php
generators/app/templates/tests/behat/features/bootstrap/FeatureContext.php
package.json

48: Code sniffer.

---

generators/app/templates/circleci/config.yml

Close https://github.com/humpbackdev/generator-humpback/issues/23

Issue 23: add pantheon multidev step to the circle ci Flow

---

generators/app/index.js
generators/app/templates/_README.md
generators/app/templates/_behat.yml
generators/app/templates/_docker-compose.yml
generators/app/templates/_site.ahoy.yml
generators/app/templates/circleci/config.yml
generators/app/templates/circleci/site.aliases.drushrc.php
generators/app/templates/gitignore

Closes #33 
See build job (and artifacts) at https://circleci.com/gh/kporras07/lighthouse/2#artifacts/containers/0

Add lighthouse.

---

generators/app/index.js

Update humpback version.

---

generators/app/index.js
generators/app/templates/circleci/config.yml
generators/app/templates/gitignore

Closes #34 
See https://circleci.com/gh/kporras07/humpback-backstop-test/3 to check that it has passed :D

Add backstop

---

.travis.yml

Add CircleCI Config validate.

---

package.json

Let's publish a new patch version.

---

generators/app/templates/circleci/config.yml

Fixed multidev deploy steps.

---

generators/app/templates/_site.ahoy.yml
package.json

Added command for installation of the site based on db backup.

---

.travis.yml
generators/app/index.js
generators/app/templates/_docker-compose.yml
package-lock.json
package.json

Updated version of humpback to 1.23

---

generators/app/index.js
package.json

85: Update humpback and generator versions.

---

generators/app/templates/_site.ahoy.yml
generators/app/templates/circleci/config.yml
generators/app/templates/env
package.json

77: Move variables to CircleCI config.

---

package-lock.json
package.json

Fix npm vulnerabilities.

---

.travis.yml
package-lock.json
package.json

How to test:
- It should pass build.

Apply security updates

---

generators/app/templates/deploy-environment/Pantheon/circleci/config.yml
generators/app/templates/deploy-environment/Pantheon/composer.json
generators/app/templates/deploy-environment/Pantheon/site.ahoy.yml
generators/app/templates/deploy-environment/Platformsh/circleci/config.yml
generators/app/templates/deploy-environment/Platformsh/composer.json
generators/app/templates/deploy-environment/Platformsh/site.ahoy.yml

- Added the install site with existing config.
- Added the drush package to Pantheon environment.
- Changed the `search_api_solr` from 3.9 to 4.

Add the import with existing config

---

README.md
generators/app/templates/docs/done.md

- Updated the `README` file with info about Platform.sh 
- Updated the `done` file.

AS-58: Update DoD of the project
